---
- name: disable SSHd reverse DNS lookup
  lineinfile: dest=/etc/ssh/sshd_config
    regexp='^\s*#*\s*UseDNS'
    line='UseDNS no'
    insertafter=EOF
  notify:
    restart SSH

- include: vagrantify_apache.yml
