sudo: false
language: php
php:
- 5.4
- 5.5
- 5.6
- 7.0

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

addons:
  postgresql: "9.3"

before_script:
- composer self-update
- composer install --prefer-source
- psql -c "create user vagrant with password 'vagrant';" -U postgres
- psql -c "create database symfony with owner vagrant;" -U postgres
- echo y | php app/console doctrine:migrations:migrate

script: phpunit -c app --coverage-clover=coverage.clover

after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover
