language: php
php:
- 5.4
- 5.5

addons:
  postgresql: "9.3"

before_script:
- composer self-update
- composer install --prefer-source
- psql -c "create user vagrant with password 'vagrant';" -U postgres
- psql -c "create database symfony with owner vagrant;" -U postgres
- echo y | php app/console doctrine:migrations:migrate

script: phpunit -c app
