managers:
    resource: "@SMGManagerBundle/Resources/config/routing.yml"

smg_oauth:
    resource: "@SMGOauthBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

users:
    resource: "@SMGUserBundle/Resources/config/routing.yml"
