# app/config/routing.yml
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

smg_oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: SMGOauthBundle:Security:login }

smg_oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: SMGOauthBundle:Security:loginCheck }

smg_oauth_server_access_token_check:
    pattern:  /oauth/access_token_valid/{accessToken}
    defaults: { _controller: SMGOauthBundle:Security:accessTokenValid }

