# app/config/routing.yml
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
smg_oauth_server_access_token_check:
    pattern:  /oauth/access_token_valid/{accessTokenString}
    defaults: { _controller: SMGOauthBundle:Security:accessTokenValid }

